title="Open Data Hub Knowledge Graph Portal (Mobility)"

[[tabGroups]]

name="Mobility"
[[tabGroups.tabs]]
name="Stations"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * {
?s a :Station .
?s rdfs:label ?l .
OPTIONAL {?s geo:defaultGeometry ?g .
?g geo:asWKT ?wkt .}
}
"""


[[tabGroups.tabs]]
name="Stations per type"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?st (COUNT(?s) AS ?count)   WHERE {
  ?s :hasStationType ?st .
}
GROUP BY ?st
ORDER BY DESC(?count)
"""

[[tabGroups.tabs]]
name="isHostedBy"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?t1 ?t2 {
?s1 sosa:isHostedBy ?s2 .
?s1 rdfs:label ?ll ; :hasStationType ?t1.
#?s1 geo:defaultGeometry [geo:asWKT ?wkt1] .
?s2 rdfs:label ?l2 ; :hasStationType ?t2 .
#?s2 geo:defaultGeometry [geo:asWKT ?wkt2] .
}
"""

[[tabGroups.tabs]]
name="ObservableProperties"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * WHERE {
?p a sosa:ObservableProperty .
?p rdfs:label ?l .
?p rdfs:comment ?c.
}
"""

[[tabGroups.tabs]]
name="Observations"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * WHERE {
?s a sosa:Sensor .
#?s sosa:isHostedBy ?p.
?s geo:defaultGeometry ?g . ?g geo:asWKT ?wkt .
?s sosa:madeObservation ?o .
?o sosa:hasSimpleResult ?v .
?o sosa:resultTime ?t .
?o sosa:observedProperty ?prop .
?prop rdfs:comment ?pc .
BIND(CONCAT( ?pc, ": ", str(?v)) AS ?wktLabel)
}
#LIMIT 100
"""

[[tabGroups.tabs]]
name="Sensors"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?st WHERE {
?s a sosa:Sensor .
?s geo:defaultGeometry ?g . ?g geo:asWKT ?wkt .
  ?s :hasStationType ?st .
#?s sosa:madeObservation ?o .
}
LIMIT 100
"""

[[tabGroups.tabs]]
name="Road"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * {
?rs a :RoadSegment ; :hasOriginStation ?ss ; :hasDestinationStation ?ds .
#?rs geo:defaultGeometry ?g .
#?g geo:asWKT ?wkt .
  ?ss geo:defaultGeometry [geo:asWKT ?oWKT] .
  ?ds geo:defaultGeometry [geo:asWKT ?dWKT] .
}
"""

[[tabGroups.tabs]]
name="Traffic Sensors"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * {
?s a :TrafficSensor .
?s rdfs:label ?wktLabel .
OPTIONAL {?s geo:defaultGeometry ?g .
?g geo:asWKT ?wkt .}
}
"""


[[tabGroups.tabs]]
name="Sensor/ObservableProperty/Observation statistics"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?st ?pc ?unit (COUNT(*) AS ?count)  (MIN(?t) AS ?min_t) (MAX(?t) AS ?max_t) (MIN(?v) AS ?min_v) (AVG(?v) AS ?avg_v) (MAX(?v) AS ?max_v)   WHERE {
#?s a sosa:Sensor .
#?s sosa:isHostedBy ?p.
#  ?s a :TrafficSensor .
  ?s :hasStationType ?st .
?s geo:defaultGeometry ?g . ?g geo:asWKT ?wkt .
?s sosa:madeObservation ?o .
?o sosa:hasSimpleResult ?v .
?o sosa:resultTime ?t .
?o sosa:observedProperty ?prop .
?prop rdfs:label ?pc .
  ?prop :hasUnit ?unit .
#BIND(CONCAT(?st, "/", ?pc, "/",  str(?v), "/", ?unit) AS ?wktLabel)
}
GROUP BY ?st ?prop ?pc ?unit
ORDER BY DESC(?count)
"""

[[tabGroups.tabs]]
name="Observation of a station (siemens->Galilei_Palermo)"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?t ?v {
  FILTER (?s = <http://ex.org/suedtirol#station/342142>) # siemens->Galilei_Palermo
  ?s a :Station .
  ?s rdfs:label ?wktLabel .
  OPTIONAL {  ?s sosa:madeObservation ?o . ?o sosa:hasSimpleResult ?v .
  ?o sosa:resultTime ?t .
  ?o sosa:observedProperty ?prop .
  FILTER (?prop = <http://ex.org/suedtirol#property/54>) # Velocita media dei veicoli
  ?prop rdfs:comment ?pc .
  ?prop :hasUnit ?unit .
  }
  OPTIONAL {?s geo:defaultGeometry ?g .
  ?g geo:asWKT ?wkt .}
}
"""

[[tabGroups.tabs]]
name="Municipality"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT * {
    ?s a :Municipality .
    ?s rdfs:label ?wktLabel .
    FILTER(LANG(?wktLabel)='it') .
    OPTIONAL {
        ?s geo:defaultGeometry ?g .
        ?g geo:asWKT ?wkt .
    }
}
"""

[[tabGroups.tabs]]
name="Covid-19"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?st ?pc ?unit ?wkt ?v ?wktLabel WHERE {
  ?s a :Covid-19 .
  ?s :hasStationType ?st .
?s geo:defaultGeometry ?g . ?g geo:asWKT ?wkt .
?s sosa:madeObservation ?o .
?o sosa:hasSimpleResult ?v .
?o sosa:resultTime ?t .
?o sosa:observedProperty ?prop .
?prop rdfs:comment ?pc .
  ?prop :hasUnit ?unit .
BIND(CONCAT(?st, "/", ?pc, "/",  str(?v), "/", ?unit) AS ?wktLabel)
}
"""

[[tabGroups.tabs]]
name="Covid and Municipality"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?mWkt ?wkt ?wktLabel {
    # Municipality
    ?m a :Municipality .
    ?m rdfs:label ?mWktLabel .
    FILTER(LANG(?mWktLabel)='it') .
    OPTIONAL {?m geo:defaultGeometry ?mg .
    ?mg geo:asWKT ?mWkt .}

    #Covid
    ?s a :Covid-19 .
    ?s :hasStationType ?st .
    ?s geo:defaultGeometry ?g . ?g geo:asWKT ?wkt .
    ?s sosa:madeObservation ?o .
    ?o sosa:hasSimpleResult ?v .
    ?o sosa:resultTime ?t .
    ?o sosa:observedProperty ?prop .
    ?prop rdfs:comment ?pc .
    ?prop :hasUnit ?unit .

    #spatial join
    FILTER(geof:sfWithin(?wkt, ?mWkt))

    #label
    BIND(CONCAT(?st, "<br>", ?mWktLabel , "<br>", ?pc, "<br>",  str(?v), "<br>", str(?t)) AS ?wktLabel)
}
"""

[[tabGroups.tabs]]
name="Covid and Municipality (OPTIONAL)"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX WV: <http://www.wurvoc.org/vocabularies/WV/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX om-2: <http://www.wurvoc.org/bibliography/om-2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?wkt ?wktLabel {
  {
    # Municipality
    ?m a :Municipality .
    ?m rdfs:label ?mWktLabel .
    FILTER(LANG(?mWktLabel)='it') .
    ?m geo:defaultGeometry ?mg .
    ?mg geo:asWKT ?mWkt .
  }
  OPTIONAL
  {
    #Covid
    ?s a :Covid-19 .
    ?s :hasStationType ?st .
    ?s geo:defaultGeometry ?g . ?g geo:asWKT ?sWkt .
    ?s sosa:madeObservation ?o .
    ?o sosa:hasSimpleResult ?v .
    ?o sosa:resultTime ?t .
    ?o sosa:observedProperty ?prop .
    ?prop rdfs:comment ?pc .
    ?prop :hasUnit ?unit .
    FILTER(?prop = <http://ex.org/suedtirol#property/5973>)
    #spatial join
    FILTER(geof:sfWithin(?sWkt, ?mWkt))
  }
  #label
  BIND(
    COALESCE(
	    CONCAT(?st, "<br>", ?mWktLabel , "<br>", ?pc, "<br>",  str(?v), "<br>", str(?t)),
      	CONCAT(?mWktLabel, "<br> (missing value)"))
    AS ?wktLabel)
  # wkt
  BIND(COALESCE(?mWkt, ?sWkt) AS ?wkt)
}
"""
