version: '3.4'

services:
  ontop-standalone:
    build:
      context: test/ontop-standalone
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/mobility/mobility.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mobility/mobility.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/mobility/mobility.docker.properties
      ONTOP_CONSTRAINT_FILE: /opt/ontop/input/odh.constraints
      ONTOP_PORTAL_FILE: /opt/ontop/input/mobility/mobility.portal.toml
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/mobility/catalog-v001.xml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      EXTRA_FLYWAY_OPTIONS: "-mixed=true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./src:/opt/ontop/src
    entrypoint: ["/wait-for-it.sh","mobility-standalone-db:5432","--timeout=0","--strict", "--", "/opt/ontop/entrypoint.sh"]
    ports:
      - "${SERVER_PORT}:8080"
  mobility-standalone-db:
    image: registry.gitlab.com/ontopic/odh-vkg-images/odh-mobility-db:standalone
    environment:
      - POSTGRES_DB=mobility
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
    ports:
      - "${DEV_MASTER_POSTGRES_PORT}:5432"
