name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cp .env.example .env

      - name: Test
        run: docker-compose --no-ansi build --pull

